//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMaleabAlKorbV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MalaebAlKorbEntities : DbContext
    {
        public MalaebAlKorbEntities()
            : base("name=MalaebAlKorbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<playerDeleteData> playerDeleteData { get; set; }
        public virtual DbSet<playerUpdateData> playerUpdateData { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<Stadium> Stadium { get; set; }
        public virtual DbSet<stadiumDeleteData> stadiumDeleteData { get; set; }
        public virtual DbSet<stadiumUpdateData> stadiumUpdateData { get; set; }
    }
}
